### ISSUE TITLE
System.IO.FileLoadException

### ISSUE THREAD

**Issue by kalaider** [kalaider/kPassKeep#1]
При попытке запуска автоматической загрузки Target по Uri на "чистом" Windows 7 с .NET Framework 4.0 Client Profile возникает неотловленное исключение:

```
Сигнатура проблемы:
  Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	kpasskeep.exe
  Сигнатура проблемы 02:	1.0.0.0
  Сигнатура проблемы 03:	5968b291
  Сигнатура проблемы 04:	PresentationCore
  Сигнатура проблемы 05:	4.0.0.0
  Сигнатура проблемы 06:	4ba1f865
  Сигнатура проблемы 07:	1a53
  Сигнатура проблемы 08:	1d
  Сигнатура проблемы 09:	System.IO.FileLoadException
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	0a9e
  Дополнительные сведения 2:	0a9e372d3b4ad19135b953a78882e789
  Дополнительные сведения 3:	0a9e
  Дополнительные сведения 4:	0a9e372d3b4ad19135b953a78882e789
```

**Comment by kalaider** [comment]
![default](https://user-images.githubusercontent.com/4180138/28239234-efb8b0f8-696f-11e7-8ec6-1598a85509b7.png)

**Comment by kalaider** [comment]
Баг не проявляется на платформах .NET 4.5 и выше.

**Comment by kalaider** [comment]
После добавления некоторого отладочного вывода был получен лог проблемы. Microsoft предлагает разные ее решения. Идет поиск верного.

```
System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at kPassKeep.Controls.TargetEdit.LoadButton_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by kalaider** [comment]
Проблема обнаружена, исправлена и ожидает внедрения в кодовую базу.

Для начала следует назвать корень проблемы -- async/await. .NET v4.0 не поддерживает async/await. Однако существует официальный backport `Microsoft.Bcl.Async`, содержащий обновленные `.dll`, позволяющий обойти это ограничение и использовать async/await в т.ч. и на .NET v4.0.

Источник "зла" async/await -- [AngleSharp](https://github.com/AngleSharp/AngleSharp), используемый для парсинга HTML -- автоматического выделения заголовка, описания и иконки сайта. Теоретически можно было бы обойтись и без async/await, однако AngleSharp уже тащит за собой `Microsoft.Bcl` и активно использует указанные фичи.

Проблема, как оказалось, состояла из двух частей.

1. `System.IO.FileLoadException` с аргументом `System.Threading.Tasks`.

    Артефакт сборки не включал `.exe.config`-файл, что вызывало исключение `System.IO.FileLoadException`. `.exe.config` содержит переопределения версий зависимостей, чтобы `Microsoft.Bcl` был корректно найден.

    Решение -- добавить в артефакт указанный файл.

2. `System.IO.FileLoadException` с аргументом `System.Core`.

    Эта ошибка связана с тем, что `Microsoft.Bcl` требует наличия в системе обновления `KB2468871`. Так что решение -- установить указанное обновление.

    Подробнее о различных проблемах с `Microsoft.Bcl` можно почитать [тут](https://blogs.msdn.microsoft.com/bclteam/p/asynctargetingpackkb/).

    Обновление может быть загружено [отсюда](https://www.microsoft.com/en-us/download/details.aspx?id=3556).

В силу того, что имеются некоторые проблемы ( #7 ), по всей вероятности вызванные именно AngleSharp, библиотека, вероятно, будет заменена на что-нибудь более приемлемое ([CsQuery](https://github.com/jamietre/CsQuery)), но замена эта пройдет не в рамках данного issue.

---

## Резюме

1. Проблема не может быть полностью решена изменением кода (требуется полный отказ от async/await и, вероятно, "пропитанного" ими AngleSharp). В любом случае требуется наличие обновления `KB2468871` в системе.
2. Решение проблемы при условии наличия указанного обновления в системе вскоре появится. Сборка с исправлением будет доступна в [AppVeyor](https://ci.appveyor.com/project/kalaider/kpasskeep) и войдет в назначенный milestone.
3. Проблема не проявляется нигде, кроме механизма автозаполнения полей, поэтому не вредит базовому использованию программы (асинхронный код используется только там). Исправление вылетов программы также будет выпущено вскоре.

**Comment by kalaider** [comment]
#10 устраняет проблему при условии наличия обновления `KB2468871`.

Требуется также "обезопасить" пользователей от нажатия на кнопку при отсутствии обновления. Это делает #11.

**Comment by kalaider** [comment]
issue закрыто. Полный отчет о симптомах и об обходе бага будет представлен здесь.

# Обзор

Баг возникает на платформах с .NET Framework версии 4.0 -- наинизшей из поддерживаемых версий. Причина бага в использовании в коде backport'а Async/Await API от Microsoft. Backport тянет за собой некоторые зависимости, которые по каким-то причинам не могут быть обнаружены.

Проблема устраняется установкой обновления `KB2468871` (https://www.microsoft.com/en-us/download/details.aspx?id=3556) или обновлением .NET Framework до версии 4.5 и выше.

# Симптомы

До применения #10 (при условии наличия #9) -- падение программы с выдачей в логе сообщения вида:

```
System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks, Version=x.x.x.x, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

После применения #10 -- падение программы со следующим логом:

```
System.IO.FileLoadException: Could not load file or assembly 'System.Core, Version=2.x.x.x, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

После применения #11 -- сообщение вида:

![image](https://user-images.githubusercontent.com/4180138/28251722-ddf4c7e0-6a8b-11e7-84d9-1543cfc7e701.png)

в дополнение к вышеприведенной записи в логе без падения программы.

# Устранение

Для полного устранения проблемы требуется установить обновление `KB2468871` (Windows XP SP3 поддерживает только этот вариант) или обновить .NET Framework до версии 4.5 и выше.

# Рекомендации

Рекомендуется заглянуть в лог для того, чтобы убедиться, что проблема именно в этом, а не в чем-то другом, найдя в логе указанную запись.

Если проблема все же в другом, следует запустить программу с флагом `-v` или `/v` и воспроизвести проблему. Сообщить о проблеме (завести новое issue), прикрепив логи.

```
cd path_to_kPassKeep_setup
kPassKeep.exe /v
```
